config/routes.rb
Rails.application.routes.draw do
  get 'trains/edit'
  resource :session, only: %i[new show create destroy]
  resources :stations, only: %i[index show new create edit update destroy]
  root 'stations#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  validates :password_digest, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                                              message: 'Invalid e-mail! Please provide a valid e-mail address'}, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :train_stations
  has_many :trains, through: :train_stations
  accepts_nested_attributes_for :train_stations, allow_destroy: true, reject_if: :blank_train?

  validates :name, presence: true

  def blank_train?(attributes)
    attributes[:train_attributes][:name].blank? && attributes[:train_attributes][:id].nil?
  end
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :train_stations
  has_many :stations, through: :train_stations

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/train_station.rb
class TrainStation < ApplicationRecord
  belongs_to :station
  belongs_to :train
  accepts_nested_attributes_for :train
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :require_authentication
  before_action :authorize_admin!
  before_action :set_admin!, only: %i[edit update destroy]

  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def update
    if @admin.update admin_params
      redirect_to admins_path
    else
      render :edit
    end
  end

  def create
    @admin = Admin.new admin_params

    if @admin.save
      redirect_to admins_path
    else
      render :new
    end
  end

  def destroy
    @admin.destroy
    redirect_to admins_path
  end

  private

  def admin_params
    params.require(:admin).permit(:email, :name, :password, :password_confirmation)
  end

  def set_admin!
    @admin = Admin.find params[:id]
  end

  def authorize_admin!
    authorize(@admin || Admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    private

    def current_user
      @current_user ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    def require_authentication
      return if user_signed_in?
      redirect_to root_path
    end

    def require_no_authentication
      return if !user_signed_in?
      redirect_to root_path
    end

    def sign_in(user)
      session[:admin_id] = user.id
    end

    def sign_out
      session.delete :admin_id
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    private

    def user_not_authorized
      redirect_to(request.referer || root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: :destroy

  def new
  end

  def create
    admin = Admin.find_by email: params[:email]

    if admin&.authenticate(params[:password])
      sign_in admin
      redirect_to root_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :require_authentication, except: %i[show index]
  before_action :set_station!, only: %i[show destroy edit update]
  before_action :fetch_train_stations, only: %i[show]

  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
    set_blank_train_stations
  end

  def create
    @station = Station.new station_params

    if @station.save
      redirect_to stations_path
    else
      render new_station_path
    end
  end

  def update
    if @station.update station_params
      redirect_to stations_path
    else
      render stations_id_path
    end
  end

  def show
  end

  def edit
    set_blank_train_stations
  end

  def destroy
    @station.destroy
    redirect_to stations_path
  end

  private

  def set_station!
    @station = Station.find_by id: params[:id]
  end

  def set_blank_train_stations
    3.times do
      train_station = @station.train_stations.build
      train_station.build_train
    end
  end

  def station_params
    params.require(:station).permit(
      :name,
      :phone,
      :address,
      :info,
      :store_info,
      train_stations_attributes: [
        :id,
        "arrival(4i)",
        "arrival(5i)",
        "departure(4i)",
        "departure(5i)",
        :_destroy,
        train_attributes: [:id, :name]
      ]
    )
  end

  def fetch_train_stations
    @train_stations = @station.train_stations.joins(:train).order('train_stations.arrival').all
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train!, only: %i[show destroy edit update]
  before_action :fetch_stations, only: %i[new edit show]

  def index
    @trains = Train.all
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new train_params

    if @train.save
      redirect_to trains_path
    else
      render new_train_path
    end
  end

  def edit
    @train_station = TrainStation.new
    @train = Train.all
  end

  def show
  end

  private

  def set_train!
    @train = Train.find_by id: params[:id]
  end

  def train_params
    params.require(:train).permit(:name)
  end

  def fetch_stations
    @stations = Station.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
      options[:class] + ' ' + css_class
    else
      css_class
    end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def full_title(page_title = "")
    base_title ="Railway"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield :main_menu %>
    <main style="margin: 20px 80px">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page %></li>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= nav_tab current_user.name, '#',
                class: 'nav-link px-2 dropdown-toggle',
                data: {"bs-toggle": 'dropdown'}, current_page: current_page %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Log out', session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Log In', new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/stations/_form.html.erb
  <%= form_for @station do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_name">Station name:</label>
    </div>
    <div class="col-sm-5">
      <%= text_field 'station', 'name', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_phone">Station phone:</label>
    </div>
    <div class="col-sm-5">
      <%= text_field 'station', 'phone', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_addres">Station address:</label>
    </div>
    <div class="col-sm-5">
      <%= text_field 'station', 'address', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_info">Information about station:</label>
    </div>
    <div class="col-sm-5">
      <%= text_field 'station', 'info', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_store_info">Store:</label>
    </div>
    <div class="col-sm-5">
      <%= text_field 'station', 'store_info', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <label for = "station_store_info">Trains schedule:</label>
    </div>
    <div class="col-sm-10">
      <%= f.fields_for :train_stations do |stations_form| %>
        <div class="mb-3">
          <%= stations_form.fields_for :train, class: "mr-3" do |train_form| %>
            <%= train_form.label :name, "Train Number" %>
            <%= train_form.text_field :name %>
          <% end %>
          <%= stations_form.label :arrival, "Arrival" %>
          <%= stations_form.time_select :arrival, { default: { hour: '0', minute: '0' } } %>
          <%= stations_form.label :departure, "Departure" %>
          <%= stations_form.time_select :departure, { default: { hour: '0', minute: '0' } } %>
          <%= stations_form.check_box :_destroy %>
          <%= stations_form.label :_destroy, 'Remove' %>
        </div>
      <% end %>
    </div>
  </div>
  <%= submit_tag "Save", class: 'btn btn-primary btn-md' %>
<% end %>

app/views/stations/edit.html.erb
<% currently_at 'Home' %>
<div class="container-sm">
  <h1 class="mb-4">Edit station</h1>
  <%= render partial: 'stations/form', locals: local_assigns %>
</div>

app/views/stations/index.html.erb
<% provide :page_title, 'Stations' %>
<% currently_at 'Home' %>
<div class="text-center mt-5">
  <h1 class="mb-4">Stations:</h1>
  <div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
    <% @stations.each do |station| %>
      <div class="col">
        <div class="card" style="width: 300px;">
          <h2 class="mb-4 card-header"><%= station.name %></h2>
          <div class="card-body">
            <%= link_to "Show", station_path(station), class: 'btn btn-secondary btn-sm', :method => :get %>
            <% if user_signed_in? %>
              <%= link_to "Edit", edit_station_path(station), class: 'btn btn-secondary btn-sm', :method => :get %>
              <%= link_to "Destroy", station_path(station), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= button_to "Add new station", new_station_path, :id => 'open-contacts-dialog-btn',
    class: 'btn btn-primary', :method => :get %>
  <% end %>
</div>

app/views/stations/new.html.erb
<% currently_at 'Home' %>
<div class="container-sm">
  <h1 class="mb-4">New station</h1>
  <%= render partial: 'stations/form', locals: local_assigns %>
</div>

app/views/stations/show.html.erb
<% currently_at 'Home' %>
<h1 class="mb-4"><%= @station.name%></h1>
<h2 class="mb-4">Station phone: <%= @station.phone%></h2>
<h2 class="mb-4">Station address: <%= @station.address%></h2>
<h2 class="mb-4">Station information: <%= @station.info%></h2>
<h2 class="mb-4">Station store info: <%= @station.store_info%></h2>
<% if @train_stations.present? %>
  <h2>Trains Schedule:</h2>
  <% @train_stations.map do |train_station| %>
    <div>
      <div class="mb-3 row">
        <div class="col-sm-1">
          <label for = "station_phone">Train Number:</label>
        </div>
        <div class="col-sm-2">
          <%= train_station.train.name %>
        </div>
        <div class="col-sm-1">
          <label for = "station_phone">Arrival:</label>
        </div>
        <div class="col-sm-1">
          <%= train_station.arrival.strftime("%H:%M") %>
        </div>
        <div class="col-sm-1">
          <label for = "station_phone">Departure:</label>
        </div>
        <div class="col-sm-1">
          <%= train_station.departure.strftime("%H:%M") %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <h2>There are no trains yet on this station.</h2>
<% end %>

app/views/trains/edit.html.erb
<h1>Trains#edit</h1>
<p>Find me in app/views/trains/edit.html.erb</p>

app/views/trains/index.html.erb
<% provide :page_title, 'Trains' %>
<% currently_at 'Trains' %>
<div class="text-center mt-5">
  <h1 class="mb-4">Trains:</h1>
  <div class="row row-cols-1 row-cols-md-5 g-4 mb-4">
    <% @trains.each do |train| %>
      <div class="col">
        <div class="card" style="width: 300px;">
          <h2 class="mb-4 card-header"><%= train.name %></h2>
          <div class="card-body">
            <%= link_to "Show", train_path(train), class: 'btn btn-secondary btn-sm', :method => :get %>
            <% if user_signed_in? %>
              <%= link_to "Edit", edit_train_path(train), class: 'btn btn-secondary btn-sm', :method => :get %>
              <%= link_to "Destroy", train_path(train), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= button_to "Add new train", new_train_path, :id => 'open-contacts-dialog-btn',
    class: 'btn btn-primary', :method => :get %>
  <% end %>
</div>

app/views/trains/new.html.erb
<% currently_at 'Trains' %>
<div class="container-sm">
  <h1 class="mb-4">New train</h1>
  <%= form_tag({:action => 'create'}, multipart: true) do %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <label for = "author_name">Train name:</label>
      </div>
      <div class="col-sm-5">
        <%= text_field 'train', 'name', required: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <%= submit_tag "Create", class: 'btn btn-primary btn-md' %>
  <% end %>
</div>